language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t davideberno/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true davideberno/docker-react npm run test